apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      initContainers:
        - name: db-init
          image: busybox
          command: [ 'sh', '-c', 'until nc -z -v -w30 airflow-postgres 5432; do echo "Waiting for migrations..."; sleep 5; done;' ]
      containers:
      - name: scheduler
        image: my/airflow_custom_build:local
        imagePullPolicy: IfNotPresent
        command: ["airflow", "scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secret
        volumeMounts:
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        - name: airflow-dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: airflow-logs
        emptyDir: {}
      - name: airflow-dags
        emptyDir: {}