apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
spec:
  template:
    spec:
      containers:
      - name: airflow-init
        image: my/airflow_custom_build:local
        imagePullPolicy: IfNotPresent
        command: ["airflow", "db", "init"]
        envFrom:
        - secretRef:
            name: airflow-secret
        - configMapRef:
            name: airflow-config
      restartPolicy: OnFailure