apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
stringData:
  _AIRFLOW_WWW_USER_USERNAME: "airflow_user"
  _AIRFLOW_WWW_USER_PASSWORD: "airflow_password"
  _AIRFLOW_WWW_USER_EMAIL: "airflow_user@mail.com"
