# Использование тега latest
FROM apache/airflow:latest
WORKDIR /opt/airflow

# Хранение credentials в Dockerfile
ENV username=airflow_user \
    password=airflow_password

COPY --chown=airflow:root ./src/* ./dags/
COPY entrypoint.sh /entrypoint.sh

USER root
RUN apt update && apt -y install procps default-jre
RUN chmod +x /entrypoint.sh

USER airflow

RUN python -m ensurepip --upgrade
RUN pip install --upgrade setuptools
RUN pip install -r ./dags/requirements_for_bad.txt

# Запуск нескольких процессов в одном контейнере
ENTRYPOINT ["/entrypoint.sh"]